// ── Local Tauri-specific modules ──────────────────────────────────
mod app_init;
pub mod cli_auth;
pub mod cli_onboarding;
mod commands;
mod globals;
mod macos_control;
mod menu_labels;
mod setup;
mod shortcuts;
mod tauri_wrappers;
mod tray;
mod window_state;

// ── Re-export all business logic from ha-core ────────────────────
// This makes `crate::agent`, `crate::session`, etc. resolve to ha-core's modules,
// eliminating the need for duplicate local copies.

pub use ha_core::acp;
pub use ha_core::agent;
pub use ha_core::agent_config;
pub use ha_core::agent_loader;
pub use ha_core::artifacts;
pub use ha_core::backup;
pub use ha_core::browser_state;
pub use ha_core::browser_ui;
pub use ha_core::canvas_db;
pub use ha_core::chat_engine;
pub use ha_core::context_compact;
pub use ha_core::crash_journal;
pub use ha_core::cron;
pub use ha_core::dashboard;
pub use ha_core::dev_tools;
pub use ha_core::docker;
pub use ha_core::failover;
pub use ha_core::file_extract;
pub use ha_core::guardian;
pub use ha_core::local_embedding;
pub use ha_core::logging;
pub use ha_core::mac_control;
pub use ha_core::memory;
pub use ha_core::memory_extract;
pub use ha_core::oauth;
pub use ha_core::onboarding;
pub use ha_core::paths;
pub use ha_core::permissions;
pub use ha_core::plan;
pub use ha_core::platform;
pub use ha_core::process_registry;
pub use ha_core::provider;
pub use ha_core::self_diagnosis;
pub use ha_core::service_install;
pub use ha_core::session;
pub use ha_core::skills;
pub use ha_core::slash_commands;
pub use ha_core::subagent;
pub use ha_core::system_prompt;
pub use ha_core::tools;
pub use ha_core::url_preview;
pub use ha_core::user_config;
pub use ha_core::weather;
#[cfg(target_os = "macos")]
pub use ha_core::weather_location_macos;

// Re-export ha-core utility functions (truncate_utf8, default_true, etc.)
pub use ha_core::{default_true, sql_opt_u64, sql_u64, truncate_utf8};

// Re-export ha-core global accessors and types
pub use ha_core::event_bus;
pub use ha_core::init_app_state;
pub use ha_core::{
    get_cron_db, get_event_bus, get_logger, get_memory_backend, get_session_db,
    get_subagent_cancels, set_event_bus,
};
pub use ha_core::{
    AppState, APP_LOGGER, CRON_DB, EVENT_BUS, MEMORY_BACKEND, SESSION_DB, SUBAGENT_CANCELS,
};

// ── Local re-exports ─────────────────────────────────────────────
pub use globals::get_app_handle;
pub(crate) use shortcuts::toggle_quickchat_window;

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    // macOS desktop-updater EXDEV guard. tauri-plugin-updater stages the new
    // `.app` under the temp dir then renames it over the installed bundle; when
    // the app runs from a different volume than the temp dir that rename fails
    // with "Cross-device link (os error 18)" and the update aborts. Override the
    // `tempfile` crate's temp dir onto the bundle's own volume so the rename
    // stays intra-volume (process-local — does NOT touch `$TMPDIR`, so child
    // processes are unaffected). Set early so it's in effect before any update.
    // No-op off macOS / non-bundle / same-volume.
    // NOTE: log::* is intentional here — AppLogger is not yet initialized.
    match ha_core::platform::redirect_updater_tmpdir_if_cross_volume() {
        ha_core::platform::UpdaterTmpdir::Redirected(dir) => log::warn!(
            "desktop updater: app volume differs from $TMPDIR; redirected TMPDIR to {} to keep the update rename intra-volume (avoids EXDEV)",
            dir.display()
        ),
        ha_core::platform::UpdaterTmpdir::CrossVolumeUnfixable => log::warn!(
            "desktop updater: app volume differs from $TMPDIR but no same-volume temp dir could be staged (read-only mount or unwritable parent); a desktop self-update may fail with a cross-device (EXDEV) error — install to /Applications to resolve"
        ),
        ha_core::platform::UpdaterTmpdir::Unchanged => {}
    }

    // Initialize directory structure
    // NOTE: log::error! is intentional here — AppLogger is not yet initialized at this point
    if let Err(e) = paths::ensure_dirs() {
        log::error!("Failed to initialize data directories: {}", e);
    }

    // Bring up the core runtime first so the legacy `"default"` → `"ha-main"`
    // agent-id rename runs BEFORE `ensure_default_agent` would otherwise
    // pre-create an empty `agents/ha-main/` template — that pre-creation
    // would block the rename and orphan the user's customised legacy data.
    // `init_runtime` is idempotent, so the later `init_tauri_app_state`
    // call is a no-op for these side effects.
    ha_core::set_app_version(env!("CARGO_PKG_VERSION"));
    ha_core::init_runtime("desktop");

    // Ensure default agent exists
    if let Err(e) = agent_loader::ensure_default_agent() {
        log::error!("Failed to ensure default agent: {}", e);
    }

    let main_window_resize_save_token = window_state::new_resize_save_token();

    tauri::Builder::default()
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_notification::init())
        .plugin(tauri_plugin_autostart::init(
            tauri_plugin_autostart::MacosLauncher::LaunchAgent,
            None,
        ))
        .plugin(tauri_plugin_single_instance::init(|app, _args, _cwd| {
            // When a second instance is launched, show and focus the existing window
            use tauri::Manager;
            if let Some(window) = app.get_webview_window("main") {
                let _ = window.show();
                let _ = window.unminimize();
                let _ = window.set_focus();
            }
        }))
        .plugin(tauri_plugin_process::init())
        .plugin(
            tauri_plugin_global_shortcut::Builder::new()
                .with_handler(shortcuts::handle_shortcut)
                .build(),
        )
        .on_window_event(move |window, event| {
            window_state::handle_main_window_event(window, event, &main_window_resize_save_token);

            // Intercept window close → hide instead of quit (app stays resident in tray)
            if let tauri::WindowEvent::CloseRequested { api, .. } = event {
                let label = window.label();
                if label == "main" || label == "quickchat" {
                    api.prevent_close();
                    let _ = window.hide();
                }
            }
        })
        .setup(setup::app_setup)
        .manage(app_init::init_tauri_app_state())
        .invoke_handler(tauri::generate_handler![
            // Provider management
            commands::provider::get_providers,
            commands::provider::add_provider,
            commands::provider::update_provider,
            commands::provider::reorder_providers,
            commands::provider::delete_provider,
            commands::provider::test_provider,
            commands::provider::test_model,
            commands::provider::get_available_models,
            commands::provider::get_active_model,
            commands::provider::set_active_model,
            commands::provider::get_fallback_models,
            commands::provider::set_fallback_models,
            commands::provider::get_vision_model,
            commands::provider::set_vision_model,
            commands::provider::get_automation_model_chain,
            commands::provider::set_automation_model_chain,
            commands::provider::has_providers,
            // Legacy auth
            commands::auth::initialize_agent,
            commands::auth::start_codex_auth,
            commands::auth::check_auth_status,
            commands::auth::finalize_codex_auth,
            commands::auth::try_restore_session,
            commands::auth::logout_codex,
            // Model & settings (legacy)
            commands::auth::get_codex_models,
            commands::auth::get_current_settings,
            commands::auth::set_codex_model,
            commands::auth::set_reasoning_effort,
            // Chat
            commands::chat::save_attachment,
            commands::chat::stage_chat_attachment,
            commands::chat::discard_chat_attachment_upload,
            commands::file_upload::file_upload_start,
            commands::file_upload::file_upload_status,
            commands::file_upload::file_upload_chunk,
            commands::file_upload::file_upload_complete,
            commands::file_upload::file_upload_discard,
            commands::chat::queue_turn_user_message,
            commands::chat::list_queued_turn_user_messages,
            commands::chat::update_queued_turn_user_message,
            commands::chat::delete_queued_turn_user_message,
            commands::chat::insert_queued_turn_user_message,
            commands::chat::cancel_queued_turn_user_message,
            commands::chat::chat,
            commands::chat::stop_chat,
            commands::runtime_tasks::cancel_runtime_task,
            // Interactive terminal
            commands::terminal::terminal_create,
            commands::terminal::terminal_list,
            commands::terminal::terminal_snapshot,
            commands::terminal::terminal_write,
            commands::terminal::terminal_resize,
            commands::terminal::terminal_close,
            // Session-scoped task list (user-actionable controls in TaskProgressPanel)
            commands::tasks::list_session_tasks,
            commands::tasks::create_session_task,
            commands::tasks::update_task_status,
            commands::tasks::delete_task,
            commands::chat::set_permission_mode,
            commands::chat::set_sandbox_mode,
            // Command approval
            commands::chat::respond_to_approval,
            commands::chat::list_pending_approvals,
            // System prompt
            commands::chat::get_system_prompt,
            // Tools info
            commands::chat::list_builtin_tools,
            // Built-in user manual (Help Center)
            commands::manual::get_manual_bundle,
            commands::manual::search_manual,
            // Skills
            commands::skills::get_skills,
            commands::skills::get_skill_detail,
            commands::skills::list_mentionable_skills,
            commands::skills::get_extra_skills_dirs,
            commands::skills::add_extra_skills_dir,
            commands::skills::remove_extra_skills_dir,
            commands::skills::discover_preset_skill_sources,
            commands::skills::toggle_skill,
            commands::skills::get_skill_env_check,
            commands::skills::set_skill_env_check,
            commands::skills::get_skill_env,
            commands::skills::set_skill_env_var,
            commands::skills::remove_skill_env_var,
            commands::skills::get_skills_env_status,
            commands::skills::get_skills_status,
            commands::skills::install_skill_dependency,
            commands::skills::list_draft_skills,
            commands::skills::activate_draft_skill,
            commands::skills::discard_draft_skill,
            commands::skills::trigger_skill_review_now,
            commands::skills::get_skills_auto_review_promotion,
            commands::skills::set_skills_auto_review_promotion,
            commands::skills::get_skills_auto_review_enabled,
            commands::skills::set_skills_auto_review_enabled,
            commands::skills::get_skills_auto_review_config,
            commands::skills::set_skills_auto_review_config,
            commands::skills::reset_skills_auto_review_config,
            commands::skills::get_skills_auto_review_recent_rejects,
            commands::skills::run_skills_curator_now,
            commands::skills::apply_skills_curator_merge,
            // SkillHub / Cloud
            commands::skillhub::cloud_get_session,
            commands::skillhub::cloud_login,
            commands::skillhub::cloud_logout,
            commands::skillhub::cloud_refresh_session,
            commands::skillhub::my_skills_list,
            commands::skillhub::my_skills_refresh_cloud,
            commands::skillhub::my_skills_submit_review,
            commands::skillhub::skillhub_search_public,
            commands::skillhub::skillhub_get_public_detail,
            commands::skillhub::skillhub_download_skill,
            commands::config::get_issue_reporting_config,
            commands::config::save_issue_reporting_config,
            commands::config::save_issue_reporting_token,
            commands::config::test_issue_reporting_connection,
            commands::misc::open_directory,
            commands::misc::reveal_in_folder,
            commands::misc::save_exported_file,
            commands::misc::open_url,
            commands::misc::write_export_file,
            commands::misc::set_dock_badge_cmd,
            commands::misc::set_tray_unread_cmd,
            // Filesystem listing & search (chat-input @ mention popper, working-dir picker)
            commands::filesystem::fs_list_dir,
            commands::filesystem::fs_create_dir,
            commands::filesystem::fs_search_files,
            // Agent management
            commands::agent_mgmt::list_agents,
            commands::agent_mgmt::list_all_agents,
            commands::agent_mgmt::reorder_agents,
            commands::agent_mgmt::get_agent_config,
            commands::agent_mgmt::get_agent_markdown,
            commands::agent_mgmt::save_agent_config_cmd,
            commands::agent_mgmt::patch_agent_model_defaults,
            commands::agent_mgmt::save_agent_markdown,
            commands::agent_mgmt::preview_agent_delete,
            commands::agent_mgmt::set_agent_enabled,
            commands::agent_mgmt::delete_agent,
            commands::agent_mgmt::render_persona_to_soul_md,
            commands::agent_mgmt::get_agent_template,
            commands::agent_mgmt::scan_openclaw_agents,
            commands::agent_mgmt::import_openclaw_agents,
            commands::agent_mgmt::scan_openclaw_full,
            commands::agent_mgmt::import_openclaw_full,
            // Memory management
            commands::memory::memory_add,
            commands::memory::memory_update,
            commands::memory::memory_toggle_pin,
            commands::memory::memory_delete,
            commands::memory::memory_get,
            commands::memory::memory_list,
            commands::memory::memory_history,
            commands::memory::memory_history_page,
            commands::memory::memory_audit_page,
            commands::memory::memory_search,
            commands::memory::claim_schema_metadata,
            commands::memory::claim_list,
            commands::memory::claim_list_page,
            commands::memory::claim_get,
            commands::memory::claim_graph,
            commands::memory::claim_conflicts,
            commands::memory::claim_conflict_details,
            commands::memory::claim_conflict_summaries,
            commands::memory::claim_evidence_summaries,
            commands::memory::claim_review_summaries,
            commands::memory::claim_update,
            commands::memory::claim_forget,
            commands::memory::memory_backfill_plan,
            commands::memory::memory_backfill_apply,
            commands::memory::memory_count,
            commands::memory::memory_episode_add,
            commands::memory::memory_episode_list_page,
            commands::memory::memory_episode_get,
            commands::memory::memory_episode_update,
            commands::memory::memory_episode_archive,
            commands::memory::memory_episode_restore,
            commands::memory::memory_procedure_add,
            commands::memory::memory_episode_promote_procedure,
            commands::memory::memory_procedure_list_page,
            commands::memory::memory_procedure_get,
            commands::memory::memory_procedure_update,
            commands::memory::memory_procedure_archive,
            commands::memory::memory_procedure_restore,
            commands::memory::memory_experience_history_page,
            commands::memory::memory_export,
            commands::memory::memory_backup_export,
            commands::memory::memory_backup_export_archive,
            commands::memory::memory_backup_export_encrypted,
            commands::memory::memory_backup_preview,
            commands::memory::memory_backup_preview_archive,
            commands::memory::memory_backup_restore_legacy,
            commands::memory::memory_backup_restore_legacy_archive,
            commands::memory::memory_backup_restore_structured,
            commands::memory::memory_backup_restore_structured_archive,
            commands::memory::memory_find_similar,
            commands::memory::memory_delete_batch,
            commands::memory::memory_import,
            commands::memory::memory_import_preview,
            commands::memory::memory_get_import_from_ai_prompt,
            commands::memory::get_memory_runtime_config,
            commands::memory::get_memory_core_budget_status,
            commands::memory::save_memory_runtime_config,
            commands::memory::memory_reembed,
            commands::memory::get_global_memory_md,
            commands::memory::save_global_memory_md,
            commands::memory::memory_health,
            commands::memory::memory_repair,
            commands::memory::memory_db_snapshot_restore_preview,
            commands::memory::memory_db_snapshot_restore,
            commands::memory::get_agent_memory_md,
            commands::memory::save_agent_memory_md,
            commands::memory::core_memory_get_cmd,
            commands::memory::core_memory_stats_cmd,
            commands::memory::core_memory_save_cmd,
            commands::memory::core_memory_conflict_get_cmd,
            commands::memory::core_memory_conflict_resolve_cmd,
            commands::memory::core_memory_topic_list_cmd,
            commands::memory::core_memory_topic_read_cmd,
            commands::memory::core_memory_topic_write_cmd,
            commands::memory::core_memory_topic_delete_cmd,
            commands::memory::core_memory_topic_search_cmd,
            commands::memory::core_memory_rebuild_index_cmd,
            commands::memory::core_memory_reload_session_cmd,
            commands::memory::core_memory_promote_cmd,
            commands::memory::pending_memory_list_cmd,
            commands::memory::pending_memory_approve_cmd,
            commands::memory::pending_memory_reject_cmd,
            commands::dreaming::dreaming_run_now,
            commands::dreaming::dreaming_run_resolver,
            commands::dreaming::dreaming_resolver_preflight,
            commands::dreaming::dreaming_run_profile,
            commands::dreaming::dreaming_list_profile_snapshots,
            commands::dreaming::dreaming_list_diaries,
            commands::dreaming::dreaming_read_diary,
            commands::dreaming::dreaming_is_running,
            commands::dreaming::dreaming_last_report,
            commands::dreaming::dreaming_idle_status,
            commands::dreaming::dreaming_list_runs,
            commands::dreaming::dreaming_get_run,
            commands::dreaming::dreaming_list_decisions,
            commands::dreaming::dreaming_list_decisions_page,
            commands::dreaming::dreaming_evidence_quote,
            // Onboarding wizard
            commands::onboarding::get_onboarding_state,
            commands::onboarding::save_onboarding_draft,
            commands::onboarding::mark_onboarding_completed,
            commands::onboarding::mark_onboarding_skipped,
            commands::onboarding::reset_onboarding,
            commands::onboarding::apply_onboarding_language,
            commands::onboarding::apply_onboarding_profile,
            commands::onboarding::apply_personality_preset_cmd,
            commands::onboarding::apply_onboarding_safety,
            commands::onboarding::apply_onboarding_skills,
            commands::onboarding::apply_onboarding_server,
            commands::onboarding::generate_api_key,
            commands::onboarding::list_local_ips,
            // Permission system v2
            commands::permission::get_protected_paths,
            commands::permission::set_protected_paths,
            commands::permission::reset_protected_paths,
            commands::permission::get_dangerous_commands,
            commands::permission::set_dangerous_commands,
            commands::permission::reset_dangerous_commands,
            commands::permission::get_edit_commands,
            commands::permission::set_edit_commands,
            commands::permission::reset_edit_commands,
            commands::permission::get_smart_mode_config,
            commands::permission::set_smart_mode_config,
            commands::permission::get_global_yolo_status,
            commands::config::get_default_agent_id,
            commands::config::set_default_agent_id,
            commands::config::get_web_search_config,
            commands::config::save_web_search_config,
            commands::config::get_web_fetch_config,
            commands::config::save_web_fetch_config,
            commands::config::get_ssrf_config,
            commands::config::save_ssrf_config,
            commands::config::get_filesystem_config,
            commands::config::save_filesystem_config,
            commands::config::patch_filesystem_config,
            commands::media_gen::get_media_gen_config,
            commands::media_gen::add_media_provider,
            commands::media_gen::update_media_provider,
            commands::media_gen::delete_media_provider,
            commands::media_gen::reorder_media_providers,
            commands::media_gen::set_media_default_chain,
            commands::media_gen::update_media_gen_defaults,
            commands::media_gen::get_media_provider_templates,
            commands::media_gen::list_media_voices,
            commands::media_gen::test_media_provider,
            commands::media_gen::get_media_gen_overview,
            commands::config::get_proxy_config,
            commands::config::save_proxy_config,
            commands::config::test_proxy,
            commands::docker::searxng_docker_status,
            commands::docker::searxng_docker_deploy,
            commands::docker::searxng_docker_start,
            commands::docker::searxng_docker_stop,
            commands::docker::searxng_docker_remove,
            // Local LLM assistant
            commands::local_llm::local_llm_detect_hardware,
            commands::local_llm::local_llm_recommend_model,
            commands::local_llm::local_llm_chat_catalog,
            commands::local_llm::local_llm_detect_ollama,
            commands::local_llm::local_llm_detect_ollama_version,
            commands::local_llm::local_llm_known_backends,
            commands::local_llm::local_llm_start_ollama,
            commands::local_llm::local_llm_list_models,
            commands::local_llm::local_llm_search_library,
            commands::local_llm::local_llm_get_library_model,
            commands::local_llm::local_llm_preload_model,
            commands::local_llm::local_llm_stop_model,
            commands::local_llm::local_llm_delete_model,
            commands::local_llm::local_llm_add_provider_model,
            commands::local_llm::local_llm_set_default_model,
            commands::local_llm::local_llm_add_embedding_config,
            commands::local_embedding::local_embedding_list_models,
            // STT (Speech-to-Text) subsystem
            commands::stt::get_stt_providers,
            commands::stt::add_stt_provider,
            commands::stt::update_stt_provider,
            commands::stt::delete_stt_provider,
            commands::stt::reorder_stt_providers,
            commands::stt::get_active_stt_model,
            commands::stt::set_active_stt_model,
            commands::stt::clear_active_stt_model,
            commands::stt::get_stt_fallback_models,
            commands::stt::set_stt_fallback_models,
            commands::stt::get_im_fallback_stt_model,
            commands::stt::set_im_fallback_stt_model,
            commands::stt::list_known_local_stt_backends,
            commands::stt::probe_local_stt_backend,
            commands::stt::upsert_known_local_stt_provider_cmd,
            commands::stt::stt_transcribe_blob,
            commands::stt::stt_start_session,
            commands::stt::stt_push_chunk,
            commands::stt::stt_finalize_session,
            commands::stt::stt_cancel_session,
            commands::local_model_jobs::local_model_job_start_chat_model,
            commands::local_model_jobs::local_model_job_start_embedding,
            commands::local_model_jobs::local_model_job_start_ollama_install,
            commands::local_model_jobs::local_model_job_start_ollama_pull,
            commands::local_model_jobs::local_model_job_start_ollama_preload,
            commands::local_model_jobs::local_model_job_list,
            commands::local_model_jobs::local_model_job_get,
            commands::local_model_jobs::local_model_job_logs,
            commands::local_model_jobs::local_model_job_cancel,
            commands::local_model_jobs::local_model_job_pause,
            commands::local_model_jobs::local_model_job_retry,
            commands::local_model_jobs::local_model_job_clear,
            commands::local_model_alerts::local_model_alert_dismiss_temporary,
            commands::local_model_alerts::local_model_alert_silence_session,
            commands::local_model_alerts::get_local_llm_auto_maintenance_enabled,
            commands::local_model_alerts::set_local_llm_auto_maintenance_enabled,
            commands::local_model_alerts::local_model_auto_maintenance_disable,
            commands::local_model_alerts::local_model_auto_maintenance_trigger,
            commands::memory::memory_stats,
            commands::memory::get_extract_config,
            commands::memory::save_extract_config,
            commands::memory::get_memory_selection_config,
            commands::memory::save_memory_selection_config,
            commands::memory::get_memory_budget_config,
            commands::memory::save_memory_budget_config,
            commands::memory::get_external_memory_providers_config,
            commands::memory::get_external_memory_providers_preflight,
            commands::memory::run_external_memory_provider_sync,
            commands::memory::get_external_memory_provider_credential_status,
            commands::memory::save_external_memory_provider_credentials,
            commands::memory::clear_external_memory_provider_credentials,
            commands::memory::save_external_memory_providers_config,
            commands::memory::get_dedup_config,
            commands::memory::save_dedup_config,
            commands::memory::get_hybrid_search_config,
            commands::memory::save_hybrid_search_config,
            commands::memory::get_temporal_decay_config,
            commands::memory::save_temporal_decay_config,
            commands::memory::get_mmr_config,
            commands::memory::save_mmr_config,
            commands::memory::get_embedding_cache_config,
            commands::memory::save_embedding_cache_config,
            commands::memory::get_multimodal_config,
            commands::memory::save_multimodal_config,
            commands::memory::get_embedding_config,
            commands::memory::save_embedding_config,
            commands::memory::get_embedding_presets,
            commands::memory::embedding_model_config_list,
            commands::memory::embedding_model_config_templates,
            commands::memory::embedding_model_config_save,
            commands::memory::embedding_model_config_delete,
            commands::memory::embedding_model_config_test,
            commands::memory::memory_embedding_get,
            commands::memory::memory_embedding_set_default,
            commands::memory::memory_embedding_disable,
            commands::memory::memory_reembed_start,
            commands::config::get_compact_config,
            commands::config::save_compact_config,
            commands::config::get_hooks_config,
            commands::config::save_hooks_config,
            commands::config::get_session_title_config,
            commands::config::save_session_title_config,
            commands::config::get_notification_config,
            commands::config::save_notification_config,
            commands::config::get_auto_update_config,
            commands::config::set_auto_update_config,
            commands::config::get_startup_notification_config,
            commands::config::save_startup_notification_config,
            commands::config::get_server_config,
            commands::config::save_server_config,
            commands::config::get_server_runtime_status,
            commands::config::compact_context_now,
            commands::config::get_awareness_config,
            commands::config::save_awareness_config,
            commands::config::get_session_awareness_override,
            commands::config::set_session_awareness_override,
            // Theme & Language
            commands::config::get_theme,
            commands::config::set_theme,
            commands::config::get_enhanced_focus_indicators,
            commands::config::set_enhanced_focus_indicators,
            commands::config::get_language,
            commands::config::set_language,
            commands::config::get_ui_effects_enabled,
            commands::config::set_ui_effects_enabled,
            commands::config::get_prevent_sleep_enabled,
            commands::config::set_prevent_sleep_enabled,
            commands::config::get_sidebar_display_mode,
            commands::config::set_sidebar_display_mode,
            commands::config::get_tool_call_narration_enabled,
            commands::config::set_tool_call_narration_enabled,
            // User config
            commands::config::get_user_config,
            commands::config::save_user_config,
            commands::config::reset_settings_section,
            commands::config::save_avatar,
            commands::config::get_system_timezone,
            // Tool timeout
            commands::config::get_tool_timeout,
            commands::config::set_tool_timeout,
            commands::config::get_timeout_policy_config,
            commands::config::save_timeout_policy_config,
            commands::config::get_approval_timeout,
            commands::config::get_approval_timeout_enabled,
            commands::config::set_approval_timeout,
            commands::config::set_approval_timeout_enabled,
            commands::config::get_approval_timeout_action,
            commands::config::set_approval_timeout_action,
            commands::config::get_unattended_approval_action,
            commands::config::set_unattended_approval_action,
            // Tool result disk persistence
            commands::config::get_tool_result_disk_threshold,
            commands::config::set_tool_result_disk_threshold,
            // Tool limits (image/pdf)
            commands::config::get_tool_limits,
            commands::config::set_tool_limits,
            // Temperature
            commands::config::get_global_temperature,
            commands::config::set_global_temperature,
            commands::config::get_global_reasoning_effort,
            commands::config::set_global_reasoning_effort,
            commands::config::get_plan_subagent,
            commands::config::set_plan_subagent,
            commands::config::get_ask_user_question_timeout,
            commands::config::get_ask_user_question_timeout_enabled,
            commands::config::set_ask_user_question_timeout,
            commands::config::set_ask_user_question_timeout_enabled,
            // Recap
            commands::config::get_recap_config,
            commands::config::save_recap_config,
            // Recall Summary
            commands::config::get_recall_summary_config,
            commands::config::save_recall_summary_config,
            // Dreaming
            commands::config::get_dreaming_config,
            commands::config::save_dreaming_config,
            commands::config::validate_cron_expression,
            // Async tool execution
            commands::config::get_async_tools_config,
            commands::config::save_async_tools_config,
            commands::config::get_cron_config,
            commands::config::save_cron_config,
            // Deferred tool loading
            commands::config::get_deferred_tools_config,
            commands::config::save_deferred_tools_config,
            // Shortcuts
            commands::config::get_shortcut_config,
            commands::config::save_shortcut_config,
            commands::config::set_shortcuts_paused,
            // Quick prompts
            commands::config::get_quick_prompt_config,
            commands::config::add_quick_prompt,
            // Weather
            commands::config::geocode_search,
            commands::config::preview_weather,
            commands::config::get_current_weather,
            commands::config::refresh_weather,
            commands::config::detect_location,
            // Autostart
            commands::config::get_autostart_enabled,
            commands::config::set_autostart_enabled,
            // Permissions (thin wrappers over ha-core)
            tauri_wrappers::check_all_permissions,
            tauri_wrappers::check_system_permissions,
            tauri_wrappers::check_permission,
            tauri_wrappers::request_permission,
            tauri_wrappers::request_system_permission,
            tauri_wrappers::mac_control_status,
            tauri_wrappers::mac_control_permissions,
            tauri_wrappers::mac_control_snapshot,
            tauri_wrappers::mac_control_elements,
            tauri_wrappers::mac_control_capture_frame,
            tauri_wrappers::mac_control_list_displays,
            tauri_wrappers::tool_recent_actions,
            // Session management
            commands::session::create_session_cmd,
            commands::session::fork_session_cmd,
            commands::session::list_sessions_cmd,
            commands::session::load_session_messages_latest_cmd,
            commands::session::load_session_messages_before_cmd,
            commands::session::load_session_messages_after_cmd,
            commands::session::load_session_messages_around_cmd,
            commands::session::load_session_artifacts_cmd,
            commands::background_jobs::list_background_jobs,
            commands::background_jobs::get_background_job,
            commands::session::load_session_environment_cmd,
            commands::session::load_session_git_diff_cmd,
            commands::git_control::load_session_git_control_cmd,
            commands::git_control::load_session_git_diff_snapshot_cmd,
            commands::git_control::mutate_session_git_index_cmd,
            commands::git_control::switch_session_git_branch_cmd,
            commands::git_control::create_session_git_branch_cmd,
            commands::git_control::commit_session_git_cmd,
            commands::git_control::push_session_git_cmd,
            commands::git_control::session_git_pr_preflight_cmd,
            commands::git_control::load_session_git_pr_feedback_cmd,
            commands::git_control::create_session_git_pr_cmd,
            commands::git_control::enable_session_git_pr_auto_merge_cmd,
            commands::git_control::handoff_session_git_cmd,
            commands::git_control::get_git_operation_run_cmd,
            commands::session::get_session_stream_state,
            commands::session::get_session_stream_snapshot,
            commands::session::search_sessions_cmd,
            commands::session::search_session_messages_cmd,
            commands::session::get_session_cmd,
            commands::session::set_session_incognito,
            commands::session::get_session_memory_policy_cmd,
            commands::session::set_session_memory_policy_cmd,
            commands::session::set_session_working_dir,
            commands::session::update_session_agent_cmd,
            commands::session::set_session_model,
            commands::session::set_session_temperature,
            commands::session::set_session_reasoning_effort,
            commands::session::get_chat_runtime_defaults,
            commands::session::purge_session_if_incognito,
            commands::session::delete_session_cmd,
            commands::session::rename_session_cmd,
            commands::session::set_session_pinned_cmd,
            commands::session::mark_session_read_cmd,
            commands::session::mark_session_read_batch_cmd,
            commands::session::mark_all_sessions_read_cmd,
            commands::session::regular_unread_total_cmd,
            commands::session::next_unread_session_cmd,
            commands::session::export_session_cmd,
            // Project management
            commands::project::list_projects_cmd,
            commands::project::get_project_overview_cmd,
            commands::project::get_project_cmd,
            commands::project::create_project_cmd,
            commands::project::update_project_cmd,
            commands::project::inspect_project_instructions_cmd,
            commands::project::get_project_instructions_cmd,
            commands::project::save_project_instructions_cmd,
            commands::project::delete_project_cmd,
            commands::project::archive_project_cmd,
            commands::project::reorder_projects_cmd,
            commands::project::list_project_sessions_cmd,
            commands::project::move_session_to_project_cmd,
            commands::project::mark_project_sessions_read_cmd,
            commands::project::list_project_memories_cmd,
            commands::project::list_project_memory_files_cmd,
            commands::project::read_project_memory_file_cmd,
            commands::project::write_project_memory_file_cmd,
            commands::project::delete_project_memory_file_cmd,
            commands::project::rebuild_project_memory_index_cmd,
            // Project file browser (workspace-scoped filesystem)
            commands::project_fs::project_fs_list,
            commands::project_fs::project_fs_capabilities,
            commands::project_fs::project_fs_read_text,
            commands::project_fs::project_fs_extract,
            commands::project_fs::project_fs_search,
            commands::project_fs::project_fs_resolve,
            commands::project_fs::preview_read_text,
            commands::project_fs::preview_extract,
            commands::project_fs::project_git_info,
            commands::project_fs::project_fs_write_text,
            commands::project_fs::project_fs_delete,
            commands::project_fs::project_fs_rename,
            commands::project_fs::project_fs_mkdir,
            commands::project_fs::project_fs_upload,
            commands::project_fs::project_fs_claim_upload,
            // Knowledge Base
            commands::knowledge::list_kbs_cmd,
            commands::knowledge::get_kb_cmd,
            commands::knowledge::create_kb_cmd,
            commands::knowledge::update_kb_cmd,
            commands::knowledge::delete_kb_cmd,
            commands::knowledge::reindex_kb_cmd,
            commands::knowledge::reindex_note_cmd,
            commands::knowledge::reindex_dir_cmd,
            commands::knowledge::kb_source_import_cmd,
            commands::knowledge::kb_source_import_browser_cmd,
            commands::knowledge::kb_source_import_session_attachment_cmd,
            commands::knowledge::kb_source_import_batch_cmd,
            commands::knowledge::kb_source_list_cmd,
            commands::knowledge::kb_source_import_runs_list_cmd,
            commands::knowledge::kb_source_import_run_detail_cmd,
            commands::knowledge::kb_source_import_retry_failed_cmd,
            commands::knowledge::kb_source_ocr_pages_cmd,
            commands::knowledge::kb_source_ocr_retry_cmd,
            commands::knowledge::kb_source_similarity_groups_cmd,
            commands::knowledge::kb_source_similarity_dismiss_cmd,
            commands::knowledge::kb_source_similarity_resolve_cmd,
            commands::knowledge::kb_source_read_cmd,
            commands::knowledge::kb_source_asset_link_cmd,
            commands::knowledge::kb_source_refresh_cmd,
            commands::knowledge::kb_source_versions_cmd,
            commands::knowledge::kb_source_diff_cmd,
            commands::knowledge::kb_source_reextract_cmd,
            commands::knowledge::kb_source_delete_cmd,
            commands::knowledge::kb_source_sync_external_raw_cmd,
            commands::knowledge::kb_compile_start_cmd,
            commands::knowledge::kb_compile_status_cmd,
            commands::knowledge::kb_compile_runs_list_cmd,
            commands::knowledge::kb_compile_proposals_list_cmd,
            commands::knowledge::kb_compile_proposal_approve_cmd,
            commands::knowledge::kb_compile_proposal_reject_cmd,
            commands::knowledge::kb_compile_run_cancel_cmd,
            commands::knowledge::kb_query_file_cmd,
            commands::knowledge::knowledge_compile_config_get_cmd,
            commands::knowledge::knowledge_compile_config_set_cmd,
            commands::knowledge::knowledge_vision_config_get_cmd,
            commands::knowledge::knowledge_vision_config_set_cmd,
            commands::knowledge::note_tools_config_get_cmd,
            commands::knowledge::note_tools_config_set_cmd,
            commands::knowledge::kb_schema_profile_cmd,
            commands::knowledge::kb_schema_issues_cmd,
            commands::knowledge::kb_note_source_refs_cmd,
            commands::knowledge::kb_evidence_coverage_cmd,
            commands::knowledge::kb_evidence_source_claims_cmd,
            commands::knowledge::kb_evidence_rebuild_cmd,
            commands::knowledge::knowledge_agent_search_cmd,
            commands::knowledge::knowledge_agent_read_cmd,
            commands::knowledge::knowledge_agent_expand_cmd,
            commands::knowledge::knowledge_agent_sources_cmd,
            commands::knowledge::knowledge_agent_compile_propose_cmd,
            commands::knowledge::attach_session_kb_cmd,
            commands::knowledge::detach_session_kb_cmd,
            commands::knowledge::attach_project_kb_cmd,
            commands::knowledge::detach_project_kb_cmd,
            commands::knowledge::list_session_kbs_cmd,
            commands::knowledge::list_project_kbs_cmd,
            commands::knowledge::list_kb_notes_cmd,
            commands::knowledge::kb_note_read_cmd,
            commands::knowledge::kb_note_save_cmd,
            commands::knowledge::kb_note_delete_cmd,
            commands::knowledge::kb_note_rename_cmd,
            commands::knowledge::kb_list_dirs_cmd,
            commands::knowledge::kb_list_tags_cmd,
            commands::knowledge::knowledge_embedding_get_cmd,
            commands::knowledge::knowledge_embedding_set_default_cmd,
            commands::knowledge::knowledge_embedding_disable_cmd,
            commands::knowledge::knowledge_embedding_rebuild_cmd,
            commands::knowledge::knowledge_chunk_get_cmd,
            commands::knowledge::knowledge_chunk_set_cmd,
            commands::knowledge::knowledge_search_config_get_cmd,
            commands::knowledge::knowledge_search_config_set_cmd,
            commands::knowledge::list_referenceable_notes_cmd,
            commands::knowledge::kb_mkdir_cmd,
            commands::knowledge::kb_rename_dir_cmd,
            commands::knowledge::kb_delete_dir_cmd,
            commands::knowledge::kb_backlinks_cmd,
            commands::knowledge::kb_broken_links_cmd,
            commands::knowledge::kb_orphans_cmd,
            commands::knowledge::kb_graph_cmd,
            commands::knowledge::kb_graph_layout_get_cmd,
            commands::knowledge::kb_graph_layout_save_cmd,
            commands::knowledge::kb_chat_thread_get_cmd,
            commands::knowledge::kb_chat_threads_list_cmd,
            commands::knowledge::kb_ai_rewrite_cmd,
            commands::knowledge::kb_rewrite_log_cmd,
            commands::knowledge::kb_maintenance_run_cmd,
            commands::knowledge::kb_maintenance_status_cmd,
            commands::knowledge::kb_maintenance_list_cmd,
            commands::knowledge::kb_maintenance_pending_count_cmd,
            commands::knowledge::kb_maintenance_approve_cmd,
            commands::knowledge::kb_maintenance_reject_cmd,
            commands::knowledge::kb_maintenance_reject_all_cmd,
            commands::knowledge::kb_maintenance_config_get_cmd,
            commands::knowledge::kb_maintenance_config_set_cmd,
            commands::knowledge::kb_passive_recall_config_get_cmd,
            commands::knowledge::kb_passive_recall_config_set_cmd,
            commands::knowledge::knowledge_media_retention_config_get_cmd,
            commands::knowledge::knowledge_media_retention_config_set_cmd,
            commands::knowledge::knowledge_source_limits_config_get_cmd,
            commands::knowledge::knowledge_source_limits_config_set_cmd,
            commands::knowledge::kb_sprite_observe_cmd,
            commands::knowledge::sprite_config_get_cmd,
            commands::knowledge::sprite_config_set_cmd,
            commands::knowledge::kb_note_read_ref_cmd,
            commands::knowledge::kb_search_cmd,
            commands::knowledge::kb_file_read_cmd,
            commands::knowledge::kb_file_extract_cmd,
            commands::knowledge::kb_file_resolve_cmd,
            // Window theme
            commands::misc::set_window_theme,
            commands::misc::get_dangerous_mode_status,
            commands::misc::set_dangerous_skip_all_approvals,
            // Logging
            commands::logging::query_logs_cmd,
            commands::logging::get_log_stats_cmd,
            commands::logging::clear_logs_cmd,
            commands::logging::get_log_config_cmd,
            commands::logging::save_log_config_cmd,
            commands::logging::export_logs_cmd,
            commands::logging::list_log_files_cmd,
            commands::logging::read_log_file_cmd,
            commands::logging::get_log_file_path_cmd,
            commands::logging::frontend_log,
            commands::logging::frontend_log_batch,
            // Cron management
            commands::cron::cron_list_jobs,
            commands::cron::cron_get_job,
            commands::cron::cron_create_job,
            commands::cron::cron_update_job,
            commands::cron::cron_delete_job,
            commands::cron::cron_toggle_job,
            commands::cron::cron_run_now,
            commands::cron::cron_jobs_referencing_account,
            commands::cron::cron_get_run_logs,
            commands::cron::cron_get_calendar_events,
            commands::cron::cron_run_timeline,
            commands::cron::cron_unread_total,
            commands::cron::cron_mark_all_read,
            // Sub-agent management
            commands::subagent::list_subagent_runs,
            commands::subagent::get_subagent_run,
            commands::subagent::get_subagent_runs_batch,
            commands::subagent::kill_subagent,
            // Team management
            commands::team::list_teams,
            commands::team::get_team,
            commands::team::get_team_members,
            commands::team::get_team_messages,
            commands::team::get_team_messages_before,
            commands::team::get_team_tasks,
            commands::team::send_user_team_message,
            commands::team::list_team_templates,
            commands::team::save_team_template,
            commands::team::delete_team_template,
            commands::team::create_team,
            commands::team::pause_team,
            commands::team::resume_team,
            commands::team::dissolve_team,
            // Crash recovery & backup
            commands::crash::get_crash_recovery_info,
            commands::crash::get_config_health,
            commands::crash::get_crash_history,
            commands::crash::clear_crash_history,
            commands::crash::request_app_restart,
            commands::crash::list_backups_cmd,
            commands::crash::restore_backup_cmd,
            commands::crash::create_backup_cmd,
            commands::crash::list_settings_backups_cmd,
            commands::crash::restore_settings_backup_cmd,
            commands::crash::get_guardian_enabled,
            commands::crash::set_guardian_enabled,
            // Slash commands (thin wrappers over ha-core)
            tauri_wrappers::list_slash_commands,
            tauri_wrappers::execute_slash_command,
            tauri_wrappers::is_slash_command,
            // Canvas (thin wrappers over ha-core)
            tauri_wrappers::canvas_submit_snapshot,
            tauri_wrappers::canvas_submit_eval_result,
            tauri_wrappers::get_canvas_config,
            tauri_wrappers::save_canvas_config,
            tauri_wrappers::list_canvas_projects,
            tauri_wrappers::list_canvas_projects_by_session,
            tauri_wrappers::get_canvas_project,
            tauri_wrappers::delete_canvas_project,
            tauri_wrappers::show_canvas_panel,
            // Artifacts (local-first control plane over Canvas storage)
            tauri_wrappers::list_artifacts,
            tauri_wrappers::get_artifact,
            tauri_wrappers::list_artifact_versions,
            tauri_wrappers::import_artifact,
            tauri_wrappers::restore_artifact,
            tauri_wrappers::verify_artifact,
            tauri_wrappers::review_artifact_export,
            tauri_wrappers::export_artifact,
            tauri_wrappers::archive_artifact,
            tauri_wrappers::delete_artifact,
            // Dashboard analytics
            commands::dashboard::dashboard_overview,
            commands::dashboard::dashboard_token_usage,
            commands::dashboard::dashboard_tool_usage,
            commands::dashboard::dashboard_sessions,
            commands::dashboard::dashboard_errors,
            commands::dashboard::dashboard_tasks,
            commands::dashboard::dashboard_control_plane,
            commands::dashboard::dashboard_system_metrics,
            commands::dashboard::dashboard_session_list,
            commands::dashboard::dashboard_message_list,
            commands::dashboard::dashboard_tool_call_list,
            commands::dashboard::dashboard_error_list,
            commands::dashboard::dashboard_agent_list,
            commands::dashboard::dashboard_overview_delta,
            commands::dashboard::dashboard_insights,
            commands::dashboard::dashboard_learning_overview,
            commands::dashboard::dashboard_learning_timeline,
            commands::dashboard::dashboard_top_skills,
            commands::dashboard::dashboard_recall_stats,
            commands::dashboard::dashboard_coding_improvement,
            commands::dashboard::dashboard_plan_stats,
            commands::dashboard::dashboard_local_model_usage,
            // Evaluation Center (isolated real-model diagnostics)
            commands::evaluation::eval_readiness,
            commands::evaluation::eval_catalog,
            commands::evaluation::eval_list_model_options,
            commands::evaluation::eval_preview,
            commands::evaluation::eval_start,
            commands::evaluation::eval_cancel,
            commands::evaluation::eval_retry,
            commands::evaluation::eval_list_history,
            commands::evaluation::eval_get_experiment,
            commands::evaluation::eval_compare,
            commands::evaluation::eval_trends,
            commands::evaluation::eval_get_trial,
            commands::evaluation::eval_set_pinned,
            commands::evaluation::eval_import_bundle,
            commands::evaluation::eval_import_unverified,
            commands::evaluation::eval_export_local_bundle,
            commands::evaluation::eval_create_baseline,
            commands::evaluation::eval_delete_baseline,
            commands::evaluation::eval_list_baselines,
            commands::evaluation::eval_create_annotation,
            commands::evaluation::eval_list_annotations,
            // Recap (deep analysis reports)
            commands::recap::recap_generate,
            commands::recap::recap_list_reports,
            commands::recap::recap_get_report,
            commands::recap::recap_delete_report,
            commands::recap::recap_export_html,
            // Developer tools (thin wrappers over ha-core)
            tauri_wrappers::dev_clear_sessions,
            tauri_wrappers::dev_clear_cron,
            tauri_wrappers::dev_clear_memory,
            tauri_wrappers::dev_reset_config,
            tauri_wrappers::dev_clear_all,
            // Plan mode
            commands::plan::get_plan_mode,
            commands::plan::set_plan_mode,
            commands::plan::get_plan_content,
            commands::plan::save_plan_content,
            commands::plan::create_owner_ask_user_question,
            commands::plan::respond_ask_user_question,
            commands::plan::get_pending_ask_user_group,
            commands::plan::get_plan_versions,
            commands::plan::load_plan_version_content,
            commands::plan::restore_plan_version,
            commands::plan::plan_rollback,
            commands::plan::get_plan_checkpoint,
            commands::plan::get_plan_file_path,
            commands::plan::cancel_plan_subagent,
            // Execution mode policy
            commands::execution_mode::get_execution_mode,
            commands::execution_mode::set_execution_mode,
            commands::execution_mode::get_workflow_mode,
            commands::execution_mode::set_workflow_mode,
            // Goals (top-level completion criteria and evidence)
            commands::goal::get_active_goal,
            commands::goal::get_autonomy_activity,
            commands::goal::get_goal,
            commands::goal::list_goal_watchdog_findings,
            commands::goal::create_goal,
            commands::goal::update_goal,
            commands::goal::pause_goal,
            commands::goal::resume_goal,
            commands::goal::clear_goal,
            commands::goal::evaluate_goal,
            commands::goal::close_goal,
            commands::goal::append_goal_follow_up,
            // Loop schedules (Phase 2.9 real recurrence control plane)
            commands::loop_control::list_loop_schedules,
            commands::loop_control::list_loop_watchdog_findings,
            commands::loop_control::get_loop_schedule,
            commands::loop_control::create_loop_schedule,
            commands::loop_control::update_loop_schedule_policy,
            commands::loop_control::run_loop_schedule_now,
            commands::loop_control::pause_loop_schedule,
            commands::loop_control::resume_loop_schedule,
            commands::loop_control::stop_loop_schedule,
            // LSP diagnostics and semantic navigation (Phase 3.2)
            commands::lsp::get_lsp_status,
            commands::lsp::get_lsp_diagnostics,
            // Context Retrieval v2 (Phase 3.5 task-aware context ranking)
            commands::context_retrieval::get_context_retrieval,
            // IDE / ACP context envelope (Phase 3.10)
            commands::ide_context::get_session_ide_context,
            commands::ide_context::save_session_ide_context,
            commands::ide_context::clear_session_ide_context,
            // Review Engine (Phase 3.3 durable local code review)
            commands::review::list_review_runs,
            commands::review::get_review_run,
            commands::review::run_code_review,
            commands::review::update_review_finding_status,
            // Smart verification selector (Phase 3.4)
            commands::verification::list_verification_runs,
            commands::verification::get_verification_run,
            commands::verification::plan_smart_verification,
            commands::verification::run_smart_verification,
            // Coding Eval task-level runner (Phase 5.1)
            commands::coding_eval::run_coding_task_eval_fixture,
            commands::coding_eval::list_coding_eval_gold_tasks,
            commands::coding_eval::run_coding_eval_gold_task_pack,
            commands::coding_eval::evaluate_coding_eval_strategy_effect,
            // Coding quality trend, improvement proposals, distillation, and promotion loop (Phase 3.11-4.4)
            commands::coding_improvement::get_coding_trend_report,
            commands::coding_improvement::list_coding_improvement_proposals,
            commands::coding_improvement::generate_coding_improvement_proposals,
            commands::coding_improvement::distill_coding_improvement_proposals,
            commands::coding_improvement::update_coding_improvement_proposal_status,
            commands::coding_improvement::preview_coding_improvement_proposal_action,
            commands::coding_improvement::apply_coding_improvement_proposal,
            commands::coding_improvement::preview_coding_improvement_proposal_promotion,
            commands::coding_improvement::promote_coding_improvement_proposal,
            commands::coding_improvement::record_coding_eval_run,
            commands::coding_improvement::evaluate_coding_eval_release_gate,
            commands::coding_improvement::evaluate_coding_learning_generalization,
            commands::coding_improvement::get_coding_benchmark_center,
            commands::coding_improvement::create_coding_benchmark_campaign,
            commands::coding_improvement::list_coding_benchmark_campaigns,
            commands::coding_improvement::get_coding_benchmark_campaign,
            commands::coding_improvement::cancel_coding_benchmark_campaign,
            commands::coding_improvement::run_coding_benchmark_campaign,
            commands::coding_improvement::get_benchmark_leaderboard,
            commands::coding_improvement::compare_benchmark_models,
            commands::coding_improvement::import_benchmark_task_pack,
            commands::coding_improvement::list_benchmark_task_packs,
            commands::coding_improvement::get_benchmark_task_pack,
            commands::coding_improvement::update_benchmark_task_pack_status,
            commands::coding_improvement::validate_benchmark_task_pack,
            commands::coding_improvement::get_benchmark_corpus_health,
            commands::coding_improvement::generate_benchmark_report,
            commands::coding_improvement::list_benchmark_reports,
            commands::coding_improvement::get_benchmark_report,
            commands::coding_improvement::mark_benchmark_report_release_evidence,
            commands::coding_improvement::evaluate_continuous_benchmark_gate,
            commands::coding_improvement::materialize_benchmark_backlog,
            commands::coding_improvement::list_benchmark_backlog,
            commands::coding_improvement::update_benchmark_backlog_status,
            // Domain workflows (Phase 7 general control plane)
            commands::domain_workflow::list_domain_workflow_templates,
            commands::domain_workflow::save_domain_workflow_template,
            commands::domain_workflow::preview_domain_workflow,
            commands::domain_workflow::record_domain_evidence,
            commands::domain_workflow::list_domain_evidence,
            commands::domain_workflow::evaluate_domain_artifact_export_guard,
            commands::domain_workflow::evaluate_domain_connector_action_guard,
            commands::domain_workflow::evaluate_domain_connector_e2e_gate,
            commands::domain_eval::list_domain_eval_tasks,
            commands::domain_eval::run_domain_eval_task,
            commands::domain_eval::run_domain_eval_fixture,
            commands::domain_eval::import_domain_eval_case,
            commands::domain_eval::record_domain_eval_calibration,
            commands::domain_eval::list_domain_eval_calibrations,
            commands::domain_eval::list_domain_eval_runs,
            commands::domain_eval::list_domain_eval_fixture_runs,
            commands::domain_eval::create_domain_eval_campaign,
            commands::domain_eval::list_domain_eval_campaigns,
            commands::domain_eval::get_domain_eval_campaign,
            commands::domain_eval::cancel_domain_eval_campaign,
            commands::domain_eval::run_domain_eval_campaign,
            commands::domain_eval::get_domain_eval_campaign_leaderboard,
            commands::domain_eval::evaluate_domain_quality_gate,
            commands::domain_eval::evaluate_domain_readiness_gate,
            commands::domain_eval::evaluate_domain_operational_gate,
            commands::domain_eval::generate_domain_soak_report,
            commands::domain_quality::list_domain_quality_runs,
            commands::domain_quality::get_domain_quality_run,
            commands::domain_quality::run_domain_quality,
            // Managed worktrees (Phase 3 durable isolation / handoff)
            commands::worktree::list_managed_worktrees,
            commands::worktree::create_managed_worktree,
            commands::worktree::get_managed_worktree,
            commands::worktree::get_project_bootstrap_run,
            commands::worktree::cancel_project_bootstrap,
            commands::worktree::archive_managed_worktree,
            commands::worktree::restore_managed_worktree,
            commands::worktree::handoff_managed_worktree,
            // Workflow runs (durable, domain-neutral dynamic orchestration)
            commands::workflow::list_workflow_runs,
            commands::workflow::list_workflow_watchdog_findings,
            commands::workflow::list_saved_workflow_templates,
            commands::workflow::save_workflow_template_from_run,
            commands::workflow::create_workflow_run_from_template,
            commands::workflow::get_workflow_run,
            commands::workflow::preview_workflow_script,
            commands::workflow::create_workflow_run,
            commands::workflow::run_workflow_run,
            commands::workflow::pause_workflow_run,
            commands::workflow::resume_workflow_run,
            commands::workflow::approve_workflow_run,
            commands::workflow::cancel_workflow_run,
            // Cross-session plan index (read-only)
            commands::plan_index::list_plans,
            commands::plan_index::resolve_plan_mention,
            // URL preview
            commands::url_preview::fetch_url_preview,
            commands::url_preview::fetch_url_favicon,
            commands::url_preview::fetch_url_previews,
            // Embedded browser
            commands::browser::browser_get_status,
            commands::browser::browser_extension_status,
            commands::browser::browser_install_native_host_manifest,
            commands::browser::browser_extension_stop_control,
            commands::browser::browser_list_profiles,
            commands::browser::browser_create_profile,
            commands::browser::browser_delete_profile,
            commands::browser::browser_launch,
            commands::browser::browser_connect,
            commands::browser::browser_disconnect,
            commands::browser::browser_capture_frame,
            commands::browser::browser_panel_navigate,
            commands::browser::browser_spawn_user_chrome,
            commands::browser::browser_doctor,
            commands::browser::browser_get_config,
            commands::browser::browser_set_config,
            commands::browser::browser_install_chromium_runtime,
            // MCP (Model Context Protocol) servers
            commands::mcp::mcp_list_servers,
            commands::mcp::mcp_get_server_status,
            commands::mcp::mcp_add_server,
            commands::mcp::mcp_update_server,
            commands::mcp::mcp_remove_server,
            commands::mcp::mcp_reorder_servers,
            commands::mcp::mcp_test_connection,
            commands::mcp::mcp_reconnect_server,
            commands::mcp::mcp_start_oauth,
            commands::mcp::mcp_sign_out,
            commands::mcp::mcp_list_tools,
            commands::mcp::mcp_get_recent_logs,
            commands::mcp::mcp_import_claude_desktop_config,
            commands::mcp::mcp_get_global_settings,
            commands::mcp::mcp_update_global_settings,
        ])
        .build(tauri::generate_context!())
        .expect("error while building tauri application")
        .run(|_app_handle, _event| {
            // macOS: clicking Dock icon when all windows are hidden → show main window.
            // RunEvent::Reopen only exists on macOS, so the variant must be cfg-gated.
            #[cfg(target_os = "macos")]
            if let tauri::RunEvent::Reopen { .. } = _event {
                use tauri::Manager;
                if let Some(window) = _app_handle.get_webview_window("main") {
                    let _ = window.show();
                    let _ = window.unminimize();
                    let _ = window.set_focus();
                }
            }
            // App is exiting → SessionEnd(other) observation hook (app-global,
            // one representative event). Best-effort: at hard exit the process
            // may tear down before a detached command hook finishes — graceful
            // delivery is the server path's awaited shutdown, not desktop quit.
            if let tauri::RunEvent::Exit = _event {
                ha_core::hooks::fire_session_end("", "other");
            }
        });
}
